### ISSUE TITLE
Debounce not working

### ISSUE THREAD

**Issue by rgr21** [mattickx/copilotignore-vscode#11]
From a clean install of 0.1.7, copilot ignore is finding .copilotignore files but not triggering on window change. Extension host log is full of the following:

> 2024-10-30 07:06:23.915 [info] ExtensionService#_doActivateExtension vscode.npm, startup: true, activationEvent: 'workspaceContains:package.json'
2024-10-30 07:06:24.108 [error] TypeError: Cannot read properties of undefined (reading 'log')
	at _trigger (/home/rgr21/.vscode/extensions/mattickx.copilotignore-vscode-0.1.7/out/extension.js:84:14)
	at Timeout._onTimeout (/home/rgr21/.vscode/extensions/mattickx.copilotignore-vscode-0.1.7/out/extension.js:39:41)
	at listOnTimeout (node:internal/timers:581:17)
	at process.processTimers (node:internal/timers:519:7)

**Comment by rgr21** [comment]
@mattickx title maybe under representing this -- I think 0.1.7 is not working at all.

**Comment by mathieumagalhaes** [comment]
Could you try with 1.0.8

I've implemented and tested:
```this.trigger = debounce(this._trigger.bind(this), 100)```

Then there might be no need to move the debounce function

**Comment by rgr21** [comment]
That works, thanks. (I confess to being no typescript developer!)

**Comment by mathieumagalhaes** [comment]
> That works, thanks. (I confess to being no typescript developer!)

No worries, thanks for noticing, I'm not sure how I missed it yesterday as it seemed to be working while developing.
Pushed 1.0.8 which in now available!
